### ISSUE TITLE
Build Instruction

### ISSUE THREAD

**Issue by SpontaneousDuck** [jboxberger/synology-gitea-jboxberger#4]
Could you include some build instructions if you get a chance? Would be nice to be able to build this myself to upgrade to newer versions sooner. Thanks!

**Comment by jboxberger** [comment]
Hi, [here](https://github.com/jboxberger/synology-gitea-jboxberger#build-instructions) we go :-)

I am not updating the package this often because of the messy versioning of the gitea/gitea docker container. When they bring out a new version, the older ones will be updated too. So if i pull a 1.9.5 today ... there will be a newer 1.9.5 in a few days... because of this i wait unitil the 1.9.6 releases an the 1.9.5 do not get updates anymore so i will have a stable versioning.

My target is to get stable realeases and to avoid any risk on data loss during update. Because of that i am moving slowly but stable :-).

I've added the build instructions for you. please give me some feedback how easy it is to understand and wether it works for you. 

Kind Regards

**Comment by SpontaneousDuck** [comment]
Pretty easy to understand! I got it all working. Might be nice to document that that "45" in the version is just the size of the package that has no effect on the build. Other than that the process worked perfectly! Thanks!
